model:
  name: "facebook/esmfold_v1"
  embedding_dim: 384
  pooling_method: "mean"

training:
  batch_size: 8
  learning_rate: 0.001
  epochs: 1
  optimizer: "adam"
  checkpoint_path: "checkpoints/checkpoint.pth"

data:
  train_path: "data/train_dataset.fasta"
  val_path: "data/validation_dataset.fasta"
  test_path: "data/test_dataset.fasta"
  embedding_path: "data/embeddings.h5"
  train_embedding_path: "data/train_embeddings.h5"
  val_embedding_path: "data/validation_embeddings.h5"
  test_embedding_path: "data/test_embeddings.h5"

output:
  save_path: "checkpoints/model.pt"
